# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


"""
The arg spec for the ioscm_command module
"""
__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################


class CommandArgs:  # pylint: disable=R0903
    """The arg spec for the ios_ping module."""

    argument_spec = {
        "commands": {"type": "list", "elements": "raw", "required": True},
        "wait_for": {"type": "list", "elements": "str", "aliases": ["waitfor"]},
        "match": {"default": "all", "choices": ["all", "any"]},
        "retries": {"default": 9, "type": "int"},
        "interval": {"default": 1, "type": "int"},
    }  # pylint: disable=C0301
